### ISSUE TITLE
Open-O-Meter Canvas in Open Document Format

### ISSUE THREAD

**Issue by diderikvw** [RE-MODEL/Phase-4-Building-community-and-your-system-map#2]
The canvas you created for the Open-O-Meter looks great! Unfortunately people who to not have InDesign and who would like to use the freedoms offered via the CC license, have to re-create it. So I did an experiment re-creating the canvas in Open Document Format. 

GitHub does not allow attaching ODF to an issue, so here is the link:
[Open-O-Meter Canvas in Open Document Format](http://think-innovation.com/wp-content/uploads/2018/02/Open-O-Meter-REMODEL-Canvas.odp)
and also the PDF export of it:
[the PDF](http://think-innovation.com/wp-content/uploads/2018/02/Open-O-Meter-REMODEL-Canvas.pdf)

Note: this is a rough 1st version to show what is possible. Improvements can be made. For example: which font was used? And is it an open licensed font?

You asked using GitHub issues for contributing, but would using Pull requests not be more useful when collaboratively working on this? Making use of the functionality in GitHub that was intended for this...

Furthermore, how would you like that I attribute DDC? The license is CC-BY-SA, but I do not know what is then an appropriate way for you to attribute. And I am also curious how attributing the original creator, OPEN!, as well, would work in this case.

**Comment by RE-MODEL** [comment]
@diderikvw Finally gotten around to approving the pull request, apologies for the delay. Also, Mads is correcting the file structure for all repo's. Thanks for the heads up!
